### ISSUE TITLE
Client secret is always required if set on client

### ISSUE THREAD

**Issue by stefanomondino** [brokenhandsio/vapor-oauth#1]
I'm creating (with the new Fluent extensions) some OAuth clients with a Vapor controller and a POST request. Ideally, this POST request should allow a super user to create as many clients he'd like with different (and possibly multiple) grant types.
There could be situations with multiple grant types wher some flow would require, as per OAuth2 specifications, the presence of a client_secret. However, other don't. An example could be a single OAuth client with password + client_credentials grant types (I don't even know if it would make practical sense anyway, but there may be cases). The presence of a client_secret would require each REST call to the oauth endpoints (with any grant type) to provide it, otherwise the `authenticateClient` function [here](https://github.com/brokenhandsio/vapor-oauth/blob/master/Sources/OAuth/OAuth2Provider.swift#L500) will raise an exception and throw out an error. 
Does it make sense?

**Comment by 0xTim** [comment]
Hmm so what you are saying is that if you had a client that used say the Password Credentials flow and the Implicit flow the implicit flow (which doesn't have a client secret) would fail?

I kinda get what you are getting at (if I'm on the right track) but I can't ever see a situation where a client wouldn't be able to save a secret in one situation (e.g. non-confidential such as a Javascript or mobile client) and then have it in another situation. Does that make sense?

**Comment by stefanomondino** [comment]
I'll try to explain what I was thinking about in a less "techy" way.

I've been using different API providers, from Facebook (definetly not using pure OAuth but some custom implementation instead), to less know providers such as Trakt.tv for movies and TV Series, or the old Instagram/Linkedin APIs.

In all of these cases, a normal user of the platform has a dedicated "developer" section where he can create it's "App" to access platform data. When I create an app, since OAuth is used, they're providing me back a cliend_id and a client_secret (sometimes the client_secret is hidden in the UI and they ask you to provide your password to show it with "show secret" button). 

Those applications have different grant_types allowed (each vendor could chose a different sub-set), the secret is always provided to the developer but it's not always required to provide it in the oauth flow (whatever it is).

In the oauth RFC it's either not clear or to complex for me to understand: where is the client_secret absolutely required? In my case, I've been using different custom APIs with refresh tokens for iOS apps and I don't recall being asked for a client secret ever (maybe bad server side implementation?). I think a good tradeoff would be to always require and validate a secret (if defined) for confidential clients and leave its validation to the grant_type implementation (always require it for client_credentials and password). But I think you've definetly a better knowledge than me about this subject, I'm just trying to understand this better :)

**Comment by 0xTim** [comment]
Hmm I see what you mean. To be honest, from what I read into the spec, it basically leaves it up to you when you **must** use the client secret, but you **should** always authenticate the client (which is this case is a client secret whenever you can. (Though Password and Client credentials **must** be authenticated for obvious reasons)

Personally I would say as an integrated, only give secrets to those clients who claim they are confidential, and if you do, always authenticate it.

**Comment by stefanomondino** [comment]
ok, makes sense 👍  thank you for your analysis!
