### ISSUE TITLE
Any plans for Vapor 3?

### ISSUE THREAD

**Issue by gperdomor** [brokenhandsio/vapor-oauth#7]
Hi... Do you have plans to migrate to V3?

**Comment by 0xTim** [comment]
Yep, definitely planning on migrating it! Given the time constraints I have at the moment I'm waiting on Fluent/Auth to stabilise before starting the work. Should be _relatively_ easy given the tests and split out of the different protocols though

**Comment by zdnk** [comment]
Fluent/Auth is out for Vapor 3 :)

**Comment by 0xTim** [comment]
It is indeed! I've started planning this in my head - should be relatively easy with no Fluent dependencies, though I'm going to have to integrate some sort of DatabaseKit logic in.

I'm currently doing SteamPress to work out how I architect and test everything then will do this one. Aiming for next month for an RC

**Comment by zdnk** [comment]
Hi @0xTim, any progress?

**Comment by 0xTim** [comment]
Hi @zdnk I'm going to put this through the Server Working Group incubation process (see [here](https://forums.swift.org/t/proposal-swiftnio-based-oauth-2-provider-project/16760)). I'm waiting on their proposal RFC to be ratified then I'll submit it through that

**Comment by wassup-** [comment]
@0xTim Any update on this? The last post on Swift forums is yours stating you updated the pitch?

**Comment by fvvliet** [comment]
hope this is going to be updated to vapor 3 soon

**Comment by Flerex** [comment]
Vapor 4 is already out. Is this package abandoned?

**Comment by 0xTim** [comment]
The package is more in hibernation. It was built for a client and on a very long todo list to update. With async/await now out it should actually be easier to update. If anyone wants to try then PRs would be great but I'll see if I can schedule some work soon

**Comment by 0xTim** [comment]
Just a heads up to everyone - work is being done at the moment to update the package to Vapor 4

**Comment by 0xTim** [comment]
Resolved by #8
